@API_BASE=http://localhost:5000/api


get {{API_BASE}}/seller/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE0MywidHlwZSI6ImFjY2Vzc190b2tlbiIsImlhdCI6MTY0ODYzNzU1Nn0.xWOjiGE3WWTtYhbsKLUk8c4NcEz6ON3iFuZ8RvWlITw




###
post {{API_BASE}}/seller/ads
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE0MywidHlwZSI6ImFjY2Vzc190b2tlbiIsImlhdCI6MTY0ODYzNzU1Nn0.xWOjiGE3WWTtYhbsKLUk8c4NcEz6ON3iFuZ8RvWlITw

{
    "permissionId":4
}


###
post {{API_BASE}}/seller/answerQuestion
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE0MywidHlwZSI6ImFjY2Vzc190b2tlbiIsImlhdCI6MTY0ODYzNzU1Nn0.xWOjiGE3WWTtYhbsKLUk8c4NcEz6ON3iFuZ8RvWlITw

{
    "answers": [
        {
            "id": 2,
            "sellerAnswer":"kufretme kafir bok gibi"
        },
        {
            "id": 3,
            "sellerAnswer": "siktir git satmıyom aq as"
        }
    ]
}
    



